-- DentNova: Feedback Table Migration
-- Run this in: Supabase → SQL Editor

CREATE TABLE IF NOT EXISTS public.feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    user_email TEXT,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Note: The created_at column is handled automatically by Postgres default now()
-- user_id and user_email will be populated by the app.

-- IMPORTANT: Disable RLS for testing, otherwise inserts from the app will fail with 401 Unauthorized
ALTER TABLE public.feedback DISABLE ROW LEVEL SECURITY;
